folio-org/ui-licenses

- src/components/Licenses/ViewLicense/ViewLicense.js
Removed the 'actionMenuItems'-prop from Pane and replaced it with the new 'actionMenu'-prop.
**Issue:** https://issues.folio.org/browse/UILIC-4
This is a part of: https://issues.folio.org/browse/STCOM-405
**Note:** I was not able to run ui-licenses on my local dev setup so I did not test these changes locally.
> UILIC-4: Remove actionMenuItems-prop from <Pane>

- package.json
This will allow Okapi to pull in the required backend module to provide the "licenses" interface. Requesting review, as there may be a reason why this wasn't included in the first place.
Towards UILIC-7.
> Add dependency on Okapi interface "licenses" version "1.0"

- CHANGELOG.md
- package.json
- src/components/ViewLicense/Sections/LicenseCustomProperties.js
Lookbehinds [aren't available in non-Chrome browsers yet](http://kangax.github.io/compat-table/es2016plus/) and apparently we aren't polyfilling/transpiling them.
This rewrites our usage of lookbehinds.
> Remove lookbehinds

- CHANGELOG.md
- package.json
- src/components/LicenseFilters/LicenseFilters.js
- src/components/LicenseFilters/index.js
- src/routes/Licenses.js
- translations/ui-licenses/en.json
- Implemented using [`SearchAndSort`'s new `renderFilters` and `onFilterChange` props](https://github.com/folio-org/stripes-smart-components/tree/master/lib/SearchAndSort) since we'll be using complex filter components eventually.
- `LicenseFilters` is where we'll be adding new filters in the future. This approach parallels `AgreementFilters` in `ui-agreements`.
- Available values for the status are fetched by `Licenses` via the `licenses/refdata/License/status` endpoint.
- `package.json` updated to apply a default filter set of showing only licenses with an `Active` status.
> ERM-12 Added ability to filter licenses by status

- package.json
- src/components/EditLicense/EditLicense.js
- src/components/LicenseFilters/LicenseFilters.js
- src/components/ViewLicense/Sections/LicenseInfo.js
- src/routes/Licenses.js
- test/ui-testing/crud.js
Added the following tests:
```    Module test: ui-licenses: basic license crud
Login > open licenses > create, view, edit license > logout
✓ should open app and navigate to Licenses (859ms)
✓ should clear default status filters (324ms)
✓ should create license with correct default values (8313ms)
✓ should create license (7346ms)
✓ should search for and find license: Fledgling License #90043 (2341ms)
✓ should edit license to: Edited License #90043 (5702ms)
✓ should reject endDate <= startDate (7813ms)
```
Tests can be run inside of `ui-licenses` via `yarn test` with the optional `--local` and `--show` arguments to run them against `localhost:3000` and display the tests in a browser, respectively.
> ERM-1 & ERM-11 License CRUD Tests

- src/components/EditLicense/EditLicense.js
- src/components/LicenseForm/Sections/LicenseFormInfo.js
- src/components/ViewLicense/Sections/LicenseInfo.js
- src/routes/Licenses.js
- test/ui-testing/crud.js
- translations/ui-licenses/en.json
- Create/Edit: New "Open ended" checkbox to control the `openEnded` field.
- End date will show a warning when it and the checkbox have a value since the end date will be overridden by the backend.
- View: **End date** is displayed as "Open ended" when the `openEnded` field is `true`.
> ERM-16: Added ability to make licenses Open Ended

- src/routes/Licenses.js
- Used `FormattedDate` to format the dates according to the current locale.
- Show "Open ended" as the end date when the license has been marked as open-ended.
> Formatted dates in search results

- src/components/ViewLicense/ViewLicense.js
- src/routes/Licenses.js
- test/ui-testing/term.js
**Before**: When editing a license, only the previously-set terms were displayed on load. This is because I read ERM-6 incorrectly.
**After**: When editing a license, the previously-set terms are displayed along with the primary terms. They are displayed in their weighted order.
> ERM-56: Always show primary terms when editing license

- src/components/ViewLicense/ViewLicense.js
Most recent agreement should be first, not last.
> ERM-125: Fixed default sort order for Linked Agreements

- src/components/LicenseForm/components/OrganizationsFieldArray.js
We save values now instead of IDs, so no need to maintain the look-up of IDs anymore and we can key off the `licensor` value directly.
> Fixed front-end licensor validation

- CHANGELOG.md
- package.json
- src/components/License/License.js
- src/components/License/sections/LicenseCoreDocs.js
- src/components/License/sections/LicenseSupplement.js
- src/components/LicenseForm/LicenseForm.js
- src/components/LicenseForm/sections/LicenseFormCoreDocs.js
- src/components/LicenseForm/sections/LicenseFormSupplement.js
- src/routes/CreateLicenseRoute.js
- src/routes/EditLicenseRoute.js
- src/routes/ViewLicenseRoute.js
- src/routes/handlers/file.js
Uses the various changes in `DocumentsFieldArray` and `DocumentCard` added in https://github.com/folio-org/stripes-erm-components/pull/65
upload, download, delete is handled by using a new `handlers` directory in the routes. This allows code reuse when we can't just one-line handlers for reasons such as not being able to use stripes-connect (like this case).
> ERM-257: Added ability to attach files to core/supplementary docs

- src/components/formSections/AmendmentFormInfo.js
- src/components/formSections/LicenseFormInfo.js
We used to have to send back just the date string bc the backend didn't support the full ISO datetime strings but now it does. This also fixes an issue like we had with ERM-262.
> ERM-262: Use full ISO datetime

- package.json
- test/ui-testing/contacts.js
[Necessary because of this change.](https://github.com/folio-org/stripes-erm-components/pull/101/files#diff-011d351e3d764dd491d904f806aa0826L174) `license` should've never been hardcoded into it.
> Fixed ID for license contacts test

- test/ui-testing/docs.js
- test/ui-testing/orgs.js
- Orgs changed their default filter values
- Stopped checking the 'Active' checkbox
- Accordion rendering got tweaked somehow so that the document elements were present but were not being filled with data.
- Expanded all accordions before `evaluate`ing
> Fixed tests

- src/settings/components/TermsConfig/TermField.js
- src/settings/components/TermsConfig/TermFieldEdit.js
- src/settings/components/TermsConfig/TermFieldView.js
- src/settings/components/TermsConfig/TermsConfigListFieldArray.js
A regression in final-form 4.18.5 (https://github.com/final-form/final-form/pull/267) resulted in nested fields not bubbling-up validation information to parent Fields.
I've filed an issue with final-form (https://github.com/final-form/final-form/issues/272) to see if this is intended or not, but this could be a workaround in the meanwhile.
> Terms Settings: Fixed enabled Save btn on mount

- src/components/AmendmentForm/AmendmentForm.js
- src/components/LicenseForm/LicenseForm.js
- test/ui-testing/crud.js
Disabling save prevents fields that are added as invalid (eg, those that require a selection) from showing their error messages. This change was originally made in https://github.com/folio-org/ui-agreements/pull/292 and is being ported here for consistency.
Also did some integration test fixes (`trim()` is required after the switch to `Headline`) and cleanup.
> Enabled save for invalid forms

- CHANGELOG.md
- package.json
- src/components/Amendment/Amendment.js
- src/components/AmendmentForm/AmendmentForm.js
- src/components/FormattedUTCDate/FormattedUTCDate.js
- src/components/FormattedUTCDate/index.js
- src/components/License/License.js
- src/components/LicenseForm/LicenseForm.js
- src/components/Licenses/Licenses.js
- src/components/viewSections/AmendmentInfo.js
- src/components/viewSections/CoreDocs.js
- src/components/viewSections/LicenseAgreements.js
- src/components/viewSections/LicenseAmendments.js
- src/components/viewSections/LicenseInternalContacts.js
- src/components/viewSections/SupplementaryDocs.js
Spinner and FormattedUTCDate were promoted to Stripes as of version 2.12.0 so we should switch to pulling them from there now.
> ERM-636: Use Spinner and FormattedUTCDate from Stripes

- src/components/Licenses/Licenses.js
- src/routes/EditLicenseRoute.js
Small piece of work to mirror ui-agreements' icon per row, replaced with licenses
> ERM-566: Display small license icon for each row

- src/components/formSections/components/TermsListField.js
Check if the `termValue` has an `id`and if it does, don't focus.
> Retain focus on the optional term name, refs ERM-630

- src/routes/CreateAmendmentRoute.js
- src/routes/CreateLicenseRoute.js
- src/routes/EditAmendmentRoute.js
- src/routes/EditLicenseRoute.js
- src/routes/ViewAmendmentRoute.js
- src/settings/components/TermsConfigForm.js
- translations/ui-licenses/en.json
- translations/ui-licenses/en_US.json
Callouts have been added upon creation/deletion/updating of licenses/amendments using the new stripes `CalloutContext`. For this to work, stripes dependencies will have to be updated across the board. I've not done that in this PR, because it's a little outside of the scope of this issue and spans several applications.
In addition, modals have been added when deleting amendments.
> ERM-723, 724, 725: Add Callouts and Deletion confirmations

- src/components/viewSections/LicenseInternalContacts.js
Fix for a bug I saw where the wrong translation ID was being used for internal contacts.
> Fixed Contacts isEmpty message

- CHANGELOG.md
- package.json
- src/components/License/License.js
- src/routes/EditLicenseRoute.js
- src/routes/ViewLicenseRoute.js
- translations/ui-licenses/en.json
- Makes the `Licenses: Delete licenses` permission set visible and assignable.
- Adds `Delete` dropdown button
- Front-end checks for whether the license has linked agreements. Disallows deletion if it does.
- Scoped `shouldRefresh` so that we don't attempt to try to fetch an `license` resource that was just deleted. Uses functionality added in https://github.com/folio-org/stripes-connect/pull/133
> ERM-748: Added ability to delete licenses

- CHANGELOG.md
- package.json
- src/components/formSections/AmendmentFormInfo.js
- src/components/formSections/LicenseFormInfo.js
- src/components/utils/index.js
- src/components/utils/parseDateOnlyString.js
See [comment](https://github.com/folio-org/ui-agreements/pull/658#issue-514364687)
> Fixes bug when Dates are not saved as entered when tenant timezone is ahead of UTC

- src/settings/components/LicensesCustomProperties.js
- translations/ui-licenses/en.json
Added translation labelOverride to CustomPropertiesSettings so that we surface deletion failures to the users again, and with a message specific to licenses.
ERM-2204
> fix: delete failure callout

- src/components/LicenseFilters/LicenseFilters.js
Previously we were using the length of the refdata list to know when to redraw. Swapping that out for a lodash `isEqual` allows for a more complicated check, including embedded labels.
ERM-2205
> fix: Filters now update after refdata label changes

- src/components/viewSections/LicenseAgreements.js
- src/routes/ViewAmendmentRoute/ViewAmendmentRoute.js
- src/routes/ViewLicenseRoute/ViewLicenseRoute.js
Tweaked namespacing of linkedAgreement fetches so that they fall in line with the convention laid out in ERM-2227. This allows Agreements then to invalidate those without caring about the endpoint Licenses uses
Also refactored LicenseAgreement to functional and changed how it decides whether linkedAgreements have changed, to avoid cached data showing up in table when we don't want it
ERM-2225, ERM-2227
> fix: Query Namespacing

- package.json
Bumped kint-components dependency to 2.8.2 to ensure we get the EBSCO-safe error handling in settings
ERM-2282
> build: Kint-Components dep

- src/routes/ViewLicenseRoute/ViewLicenseRoute.js
Currently the Tags component relies on the invalidation for licenses being the same as its fetch endpoint, added comment to this effect
ERM-2297
> chore: Tags invalidation comment

- src/components/viewSections/CoreDocs.js
fix: CoreDocs Category
Used new `hideCategory` prop on DocumentCard to enable the hiding of Category KeyValue in certain circumstances, namely in the Core Doc use case
ERM-2366
> ERM-2366: Core documents for a License shouldn't display a category

- src/components/Licenses/Licenses.js
Moved LicenseFilters outside of the <form> rendered for the Search field. This stops the issue where CustomPropertiesFilters was throwing a console error due to a nested <form> component
ERM-2398
> fix: LicenseFilters

- package.json
build: @rehooks/local-storage
Removed lock on @rehooks/local-storage
ERM-3037
> ERM-3037: unlock @rehooks/local-storage from 2.4.4

- src/components/viewSections/LicenseHeader/LicenseHeader.css
> ERM-3182 Scrolling content in license view pane can overlap header

- package.json
* removed 'moment' library from package.json file
> ERM-3165, Replace moment with dayjs across app suite

- package.json
- Add licenses.files.view as a sub permission of ui-licenses.licenses.file.download in ui-licenses package.json 
MERGE AFTER https://github.com/folio-org/mod-licenses/pull/267/files
> ERM-3285: Fix permission on /licenses/files/{id}/raw in mod-licenses

- CHANGELOG.md
- package.json
Added changelog section and bumped version number to 11.0.2
- ERM-3285 Fix permission on /licenses/files/{id}/raw in mod-licenses
ERM-3293
> chore: Release 11.0.2

- package.json
Removed previously required nwsapi resolution pinning version to 2.2.13, issues caused have been resolved as of 2.2.16 release
> build: Removed nswapi resolution
