CHANGELOG.md, package.json
Support more flexible semver for usage in `platform-erm`
=> Update version to 1.0

src/components/Licenses/ViewLicense/Sections/LicenseCustomProperties.js, src/components/Licenses/ViewLicense/Sections/LicenseInfo.js, src/components/Licenses/ViewLicense/ViewLicense.js, src/routes/Licenses.js
PropType validation as discussed via slack
=> Uilic 5 fix eslint issues

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/es.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20181128T202334

translations/ui-licenses/ar.json, translations/ui-licenses/pt_PT.json
=> Update translation strings as of 20181212T135930

src/components/Licenses/EditLicense/EditLicense.js
`times` replaced `closeX` some time ago.
=> don't use deprecated icons

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190130T201814

translations/ui-licenses/ar.json, translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20190221T143454

CHANGELOG.md, package.json, src/components/LicenseForm/Sections/LicenseFormInfo.js, src/components/LicenseForm/Sections/LicenseFormOrganizations.js, src/components/LicenseForm/Sections/LicenseFormTerms.js, src/components/LicenseForm/Sections/index.js, src/components/ViewLicense/Sections/LicenseHeader.css, src/components/ViewLicense/Sections/LicenseHeader.js, src/components/ViewLicense/Sections/LicenseInfo.js, src/components/ViewLicense/Sections/LicenseOrganizations.js, src/components/ViewLicense/Sections/LicenseTerms.js, src/components/ViewLicense/Sections/index.js, src/components/ViewLicense/ViewLicense.js, src/routes/Licenses.js, test/ui-testing/orgs.js, translations/ui-licenses/en.json
- Added ability to create, read, update and delete organisations for a license.
- Added integration tests for that functionality.
- Added a `sticky` header area when viewing a license.
=> ERM-7, ERM-30, ERM-31: Added ability to manage License Organizations

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190222T002228

translations/ui-licenses/ar.json
=> Update translation strings as of 20190227T140407

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190228T144944

src/routes/Licenses.js
Used when a plugin is passing props through to SearchAndSort
=> Pass props through to SAS

CHANGELOG.md, package.json, src/components/ViewLicense/ViewLicense.js, src/components/ViewLicense/sections/LicenseAgreements.js, src/components/ViewLicense/sections/index.js, translations/ui-licenses/en.json
Added ability to view agreements linked to a license.
=> ERM-63: View Linked Agreements

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190313T213403

translations/ui-licenses/ar.json, translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20190314T195719

package.json, src/components/ViewLicense/sections/LicenseTerms.js
* modify LicenseTerms.js to use shared component LicenseTermsList from stripes-erm-components
* `yarn test-text-term --local` and `yarn test-select-term --local` ran successfully
=> ERM-97: Update existing license terms view to use shared component

src/components/EditLicense/EditLicense.js
=> Added ID to close-pane button

translations/ui-licenses/es_ES.json
=> Update translation strings as of 20190425T181703

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190510T130015

translations/ui-licenses/ar.json
=> Update translation strings as of 20190510T131615

src/components/LicenseForm/components/TermsListField.js, src/routes/EditLicenseRoute.js, translations/ui-licenses/en.json
* Added the ability to add/edit license term notes.
* Viewing license term notes is being added in https://github.com/folio-org/stripes-erm-components/pull/60
=> ERM-132 ERM-145: Add/edit license term notes

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190513T134002

src/routes/CreateLicenseRoute.js, src/routes/EditLicenseRoute.js, test/ui-testing/contacts.js
Also use the new license contact roles.
=> Handle regression of autorefresh of resources

translations/ui-licenses/ar.json, translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20190517T183537

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190606T155546

CHANGELOG.md, package.json, src/components/formSections/FormCoreDocs.js, src/components/formSections/FormSupplementaryDocs.js, src/routes/components/withFileHandlers.js
Release for Q2
- Forces a bump to stripes-erm-components 1.4.0 for the new handling of file upload deletions.
=> Release v3.2.1

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190624T123511

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190627T152539

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190703T132726

src/components/Amendment/Amendment.js, src/components/AmendmentForm/AmendmentForm.js, src/components/License/License.js, src/components/LicenseForm/LicenseForm.js, src/components/formSections/LicenseFormInfo.js, src/components/formSections/LicenseFormInternalContacts.js, src/components/formSections/LicenseFormOrganizations.js, src/components/formSections/index.js, src/components/viewSections/LicenseInfo.js, src/components/viewSections/LicenseInternalContacts.js, src/components/viewSections/LicenseOrganizations.js, src/components/viewSections/index.js, test/ui-testing/amendments.js, test/ui-testing/contacts.js, test/ui-testing/docs.js, test/ui-testing/notes-crud.js, test/ui-testing/orgs.js, test/ui-testing/term.js
- Accordions in forms are now open by default
- Removed nested accordions
- Pulled "License info" out of an accordion
=> ERM-341 ERM-342: Accordion cleanup

src/components/FormattedUTCDate/FormattedUTCDate.js, src/components/FormattedUTCDate/index.js, src/components/Licenses/Licenses.js, src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js, src/components/formSections/LicenseFormOrganizations.js, src/components/viewSections/AmendmentInfo.js, src/components/viewSections/LicenseAgreements.js, src/components/viewSections/LicenseAmendments.js, src/components/viewSections/LicenseInfo.js
Mirroring the similar changes introduced in [ui/mod]-agreements to handle the changed behaviour of mod-licenses.
=> ERM-294: Switch to UTC dates within Licenses

src/components/formSections/FormTerms.js, src/components/formSections/components/TermsListField.js, test/ui-testing/select-term.js, test/ui-testing/term.js, test/ui-testing/text-term.js, translations/ui-licenses/en.json
change terms in edit pane
* use card component
* add public note
* change note to internal note
* add visibility
=> ERM-355: Manage public notes on license term values

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190807T131714

src/components/viewSections/LicenseAgreements.js
Link was the old one with the `/view/` part
=> Fixed href for linked agreements

CHANGELOG.md, src/components/viewSections/LicenseInternalContacts.js
Using the new `InternalCardComponent` introduced in https://github.com/folio-org/stripes-erm-components/pull/102
=> ERM-309: Render internal contacts as cards

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20190815T130307

translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20190828T202658

CHANGELOG.md, package.json, src/components/viewSections/LicenseOrganizations.js, src/routes/ViewLicenseRoute.js
Added show/hide credentials functionality to licenses
=> add show/hide credentials functionality to licenses, refs ERM-431, ERM-433

CHANGELOG.md, package.json, src/components/Licenses/Licenses.js, src/components/viewSections/LicenseInfo.js
- Update stripes dependency to 2.10.1
- Update CHANGELOG
=> Preserve line-break characters for paragraph fields, refs ERM-444

src/settings/routes/PickListValueSettings.js
Fetch the max number of pick lists (and sort them while we're at it).
=> ERM-471: Fetch more pick lists

translations/ui-licenses/ar.json
=> Update translation strings as of 20191004T135530

src/components/AmendmentForm/AmendmentForm.js, src/components/LicenseForm/LicenseForm.js, src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js
Use the `subscription` prop to fetch forms values instead of using the _form.getState()_ function
=> cleanup logic to fetch forms current values

src/components/Licenses/Licenses.js, src/index.js, src/routes/LicensesRoute.js
Added an isSelected to the MultiColumnList in Licenses so that the selected row fits FOLIO standard colouring.
=> PR for ERM-513

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/ru.json, translations/ui-licenses/zh_CN.json, translations/ui-licenses/zh_TW.json
=> Update translation strings as of 20191022T162142

src/routes/LicensesRoute.js
=> ERM-523: alphasort tags in SAS filter

src/routes/EditLicenseRoute.js, src/routes/ViewLicenseRoute.js
ERM-530 was really about getting rid of the error `alert()` when fetching a deleted user, but it exposed the fact that:
1. This bug doesn't exist on ui-agreements bc
2. ...ui-agreements doesn't use the `GET` mutator bc
3. ..it uses functional `params` and autoupdates the records by itself rather than needing lifecycle hooks.
So I just refactored ui-licenses to use functional `params` instead.
=> ERM-530: Refactor resource joins in manifest

translations/ui-licenses/ja.json
=> Update translation strings as of 20191101T131808

test/ui-testing/contacts.js, test/ui-testing/orgs.js
Handles changes introduced in https://github.com/folio-org/stripes-erm-components/pull/135 for ERM-451, 452 and 453
=> Updated tests to handle new linked record UX

src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js, src/routes/EditLicenseRoute.js, src/routes/ViewLicenseRoute.js
Mirroring the changes made in https://github.com/folio-org/ui-agreements/pull/353
=> ERM-579: Fix clearing of optional attributes

src/components/LicenseForm/LicenseForm.js
- Something changed in final-form 4.18.6 so iV isn't being
updated properly. Switched to use `values` instead until
the bug is fixed.
- https://github.com/final-form/final-form/issues/300
=> Don't rely on props.initialValues

src/components/viewSections/LicenseOrganizations.js
=> ERM-605: Fix organizations icon

CHANGELOG.md, src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js, test/ui-testing/orgs.js
- Lots of autofocus fixes using the technique of setting the `name` of a `<button>` which I learned working on https://github.com/folio-org/stripes-erm-components/pull/161
- Updated tests to handle refactored OrganizationsFieldArray in https://github.com/folio-org/stripes-erm-components/pull/167
=> ERM-593: Fixed autofocus

src/components/Amendment/Amendment.js, src/components/License/License.js, translations/ui-licenses/en.json
use new translationKeys for 'Delete' and 'Edit' in Amendment and License
=> ERM-594: Licenses / Amendments preview: name menu options correctly

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20191218T142024

translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json
=> Update translation strings as of 20191223T213508

CHANGELOG.md, package.json
Also renamed the Settings permissions per [ERM-616](https://issues.folio.org/browse/ERM-616)
=> ERM-615: Hid "Delete License" perm

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/he.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/ja.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/ru.json, translations/ui-licenses/zh_CN.json, translations/ui-licenses/zh_TW.json
=> Update translation strings as of 20200106T223901

translations/ui-licenses/ar.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20200109T152437

src/routes/CreateAmendmentRoute.js, test/ui-testing/amendments.js
change handleSubmit in CreateAmendmentRoute
change amendments test
=> ERM-454 Display the Amendment record when a new Amendment is added

src/components/formSections/FormCoreDocs.js, src/components/formSections/FormSupplementaryDocs.js
replace deleteButtonTooltipText with deleteBtnTooltipMsgId in FieldArray component of FormCoreDocs and FormSupplementaryDocs
=> ERM-669 Adding documents to licenses or amendments fails

translations/ui-licenses/fr_FR.json
=> Update translation strings as of 20200117T173544

test/ui-testing/amendments.js, test/ui-testing/crud.js
workaround for typing term label
=> ERM-670 amendments test fails

src/components/formSections/components/TermsListField.js, translations/ui-licenses/en.json
validate integer terms as whole numbers
=> ERM-645 Custom Properties values should enforce type in UI/Backend

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/he.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/ja.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/ru.json, translations/ui-licenses/zh_CN.json, translations/ui-licenses/zh_TW.json
=> Update translation strings as of 20200127T144839

src/index.js, test/ui-testing/term-config.js
Lazy load top level route components similar to how we do it in agreements https://github.com/folio-org/ui-agreements/pull/416
=> Introduce route based code-splitting in licenses

test/ui-testing/notes-crud.js, test/ui-testing/orgs.js
fix nightmare tests orgs and notes-crud
=> ERM-692 Support new Actions dropdown in Pane Header

translations/ui-licenses/ar.json, translations/ui-licenses/es_419.json
=> Update translation strings as of 20200211T224145

src/components/Licenses/Licenses.js, src/routes/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute.js, src/routes/EditAmendmentRoute.js, src/routes/EditLicenseRoute.js
This PR converts the `onSubmit` handler to an async function by returning a Promise out of it. React Final Form will now set the various submitting/etc `formState` props based on the Promise's status.
=> Disable Save button on form submission

src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js
`value` and `checked` for the stripes-components `CheckBox` component are 2 different things and checked prop is the one that marks the checkbox as checked or unchecked
=> Use checked prop instead of value, fixes ERM-770

translations/ui-licenses/ar.json, translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/en_GB.json, translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/he.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/ja.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/ru.json, translations/ui-licenses/ur.json, translations/ui-licenses/zh_CN.json, translations/ui-licenses/zh_TW.json
=> Update translation strings as of 20200403T124750

translations/ui-licenses/pt_BR.json
=> Update translation strings as of 20200409T134057

src/components/Licenses/Licenses.js
Wrong usage of `prevState` by me, my bad 🤦
=> Fix bug when selecting licenses

src/settings/components/TermsConfigForm.js, translations/ui-licenses/en.json
* pass name value in translation key
=> ERM-942 Error message on unsuccessful attempt to delete term omits name

translations/ui-licenses/en_US.json
=> Update translation strings as of 20200609T205925

translations/ui-licenses/ca.json, translations/ui-licenses/da.json, translations/ui-licenses/de.json, translations/ui-licenses/es.json, translations/ui-licenses/es_419.json, translations/ui-licenses/es_ES.json, translations/ui-licenses/fr.json, translations/ui-licenses/fr_FR.json, translations/ui-licenses/he.json, translations/ui-licenses/hu.json, translations/ui-licenses/it_IT.json, translations/ui-licenses/pt_BR.json, translations/ui-licenses/pt_PT.json, translations/ui-licenses/ur.json, translations/ui-licenses/zh_CN.json, translations/ui-licenses/zh_TW.json
=> Update translation strings as of 20200615T161518

translations/ui-licenses/en_SE.json, translations/ui-licenses/en_US.json
=> Update translation strings as of 20200615T202100

translations/ui-licenses/ru.json
=> Update translation strings as of 20200723T131158

src/components/LicenseFilters/LicenseFilters.js, src/routes/LicensesRoute.js
refs ERM-1043
* separate organisation and role filter
refs ERM-1045
* add description to license search
=>  ERM-1043 separate organisation and role filter

translations/ui-licenses/zh_CN.json
=> Update translation strings as of 20200824T140725

translations/ui-licenses/it_IT.json
=> Update translation strings as of 20200827T215834

translations/ui-licenses/it_IT.json
=> Update translation strings as of 20201013T203429

src/routes/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute.js, src/routes/EditAmendmentRoute.js, src/routes/EditLicenseRoute.js, src/routes/LicensesRoute.js
* add perPage param to license routes
=> ERM-1193 Load 100 values from a user definable pick lists in licenses

translations/ui-licenses/ar.json
=> Update translation strings as of 20201105T151643

src/components/Amendment/Amendment.js, src/components/DuplicateAmendmentModal/DuplicateAmendmentModal.js, src/components/DuplicateAmendmentModal/index.js, src/routes/ViewAmendmentRoute.js, test/bigtest/interactors/duplicate-amendment-modal.js, test/bigtest/tests/duplicate-amendment-modal-test.js, translations/ui-licenses/en.json
Added option to clone amendments, following same patterns as for licenses.
=> ERM-1229: Added duplicate button to amendment view screen

src/components/viewSections/AmendmentLicense.js
Removed license description, tweaked parent license headline size and margin as per QA
=> ERM-1176: QA tweaks

CHANGELOG.md, src/components/Amendment/Amendment.js, src/components/License/License.js, src/components/Licenses/Licenses.js, test/ui-testing/amendments.js, test/ui-testing/contacts.js, test/ui-testing/crud.js, test/ui-testing/docs.js, test/ui-testing/notes-crud.js, test/ui-testing/orgs.js, test/ui-testing/tags-crud.js, test/ui-testing/term.js
* remove edit button in license view
* move create license function in actions dropdown
* add comment in nightmare tests
* update CHANGELOG.md
=> ERM-1149 consolidate Edit and New under the Actions menu button

src/index.js, translations/ui-licenses/en.json
* use KeyboardShortcutsModal and NavList component in App
=> ERM-1732 display the keyboard shortcuts modal

src/components/Amendment/Amendment.js, src/components/viewSections/LicenseAgreements.js, src/routes/ViewAmendmentRoute.js, translations/ui-licenses/en.json, translations/ui-licenses/en_US.json
* add linkedAgreements to ViewAmendmentRoute manifest
* pass it to view and LicenseAgreement component
* make visibleColumns a prop, refs ERM-1694
* add amendmentLinkStatus column to MCL
* add translations
* use different accordion labels in amendment view for linked agreements
=> ERM-1694 Add list of linked agreements to Amendments view

src/components/formSections/AmendmentFormInfo.js, src/components/formSections/LicenseFormInfo.js, src/routes/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute.js
Moved endDateSemantics setting into submit handler on frontend to better reflect modelling choices
ERM-1849
=> fix: ERM-1849

package.json, test/bigtest/tests/pick-list-test.js
Bumped dependency on eslint-config-stripes to 6.0.0
ERM-1971
=> chore: eslint-config-stripes

src/routes/ViewLicenseRoute.js
* store credentials in an array constant per license to not loose once fetched ones
=> ERM-1982 Organization interface credentials malfunction

package.json, src/constants/endpoints.js, src/settings/index.js, translations/ui-licenses/en.json
Added dependency on stripes-kint-components, using useSettings to display AppSettings panel. Translations added. Added endpoints constants
ERM-1945
=> feat: AppSettings

src/routes/components/withFileHandlers.js, src/routes/components/withFileHandlers.test.js
* add test for withFileHandlers
* remove handleDeleteFile
=> ERM-1506 Add test coverage for ui-licenses withFileHandlers

src/settings/routes/PickListValueSettings.js, src/settings/routes/PickListValueSettings.test.js
* add test for PickListValueSettings
* import stripesConnect in PickListValueSettings
=> ERM-1508 Add test coverage for ui-licenses PickListValueSettings

src/settings/routes/PickListSettings.js, src/settings/routes/PickListSettings.test.js
* add test for PickListSettings
* import stripesConnect in PickListSettings
=> ERM-1507 Add test coverage for ui-licenses PickListSettings

src/settings/routes/TermsConfigRoute.test.js
* add test for TermsConfigRoute component
=> ERM-1509 Add test coverage for ui-licenses TermsConfigRoute

package.json, src/settings/components/LicensesCustomProperties.js, translations/ui-licenses/en.json
Bumped version of stripes-kint-components to take advantage of the new support for date type custprops and retired custprops
Refs ERM-778, ERM-2017, ERM-2044
=> feat: Changelog enhancements

package.json, src/components/Amendment/Amendment.js, src/components/Amendment/Amendment.test.js, src/components/License/License.js, src/components/LicenseForm/LicenseForm.test.js, src/components/formSections/FormCoreDocs/FormCoreDocs.js, src/components/formSections/FormSupplementaryDocs/FormSupplementaryDocs.js, src/components/utils/getRefdataValuesByDesc.js, src/components/viewSections/CoreDocs.js, src/components/viewSections/SupplementaryDocs.js, src/hooks/index.js, src/hooks/useLicenseRefdata.js, src/hooks/useLicensesHelperApp.js, src/routes/CreateAmendmentRoute/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute.js, src/routes/EditAmendmentRoute.js, src/routes/EditLicenseRoute.js, src/routes/LicensesRoute.js, src/routes/ViewAmendmentRoute/ViewAmendmentRoute.js, src/routes/ViewAmendmentRoute/ViewAmendmentRoute.test.js, src/routes/ViewLicenseRoute/ViewLicenseRoute.js, src/routes/ViewLicenseRoute/ViewLicenseRoute.test.js, src/routes/components/withFileHandlers.js, src/routes/components/withFileHandlers.test.js
=> refactor: licenses

package.json, src/settings/components/LicensesCustomProperties.js, translations/ui-licenses/en.json
* add new labelOverrides and helpPopovers
=> ERM-2173 New / Edit supplementary property and Term modals: UX improvements

src/components/utils/getRefdataValuesByDesc.js, src/components/utils/index.js, src/routes/CreateAmendmentRoute/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute.js, src/routes/EditAmendmentRoute.js, src/routes/EditLicenseRoute.js, src/routes/LicensesRoute.js
Moved utility function to stripes-erm-components to cut down on code reuse
=> refactor: getRefdataValuesByDesc

package.json
Bumped kint-component dependency
ERM-2158, ERM-2159
=> build: Kint-components

src/hooks/useLicenseRefdata.js
Refactored useLicenseRefdata to make slightly more useful down the road
=> refactor: useLicenseRefdata

package.json, src/settings/routes/PickListSettings.js, src/settings/routes/PickListSettings.test.js, src/settings/routes/PickListValueSettings.js, src/settings/routes/PickListValueSettings.test.js, test/jest/refdata.js, translations/ui-licenses/en.json
Moved pick list settings over to stripes-kint-components implementation
ERM-2216
=> feat: Migrated to stripes-kint-components

src/components/Amendment/Amendment.test.js, src/components/AmendmentForm/AmendmentForm.test.js, src/components/LicenseFilters/LicenseFilters.js, src/components/LicenseFilters/LicenseFilters.test.js, src/components/LicenseForm/LicenseForm.test.js, src/routes/CreateAmendmentRoute/CreateAmendmentRoute.test.js, src/settings/routes/PickListSettings.test.js, src/settings/routes/PickListValueSettings.test.js
Shifted to new kint components mocks
=> test: Kint components

CHANGELOG.md, package.json
Added changelog section and bumped version
ERM-2291
=> chore: Release 8.2.2

CHANGELOG.md
Added changelog section from patch release 8.2.2
ERM-2291
=> docs: Post-Release 8.2.2

package.json
=> build: Babel core

package.json
* add version 16.0 to package.json
=> ERM-2283 Upgrade Users interface to 16.0

package.json
* add stripes-erm-components as peer and dev dependency
* remove it from 'dependencies'
=> ERM-2321 stripes-erm-components should be a peer

src/components/viewSections/LicenseInfo/LicenseInfo.js, src/components/viewSections/LicenseInfo/LicenseInfo.test.js, src/components/viewSections/LicenseInfo/index.js
* move component to a folder
* create index file
* write test
* add MCL id to component
=> ERM-2266 Add test coverage for ui-licenses viewSections LicenseInfo

src/routes/NoteCreateRoute/NoteCreateRoute.js, src/routes/NoteCreateRoute/NoteCreateRoute.test.js, src/routes/NoteCreateRoute/index.js
* create new directory, move component
* write test
* create index file
=> ERM-2274 Add test coverage for ui-licenses routes NoteCreateRoute

src/routes/NoteEditRoute/NoteEditRoute.js, src/routes/NoteEditRoute/NoteEditRoute.test.js, src/routes/NoteEditRoute/index.js
* create directory, move component
* write test
* create index file
=> ERM-2275 Add test coverage for ui-licenses routes NoteEditRoute

src/components/AmendmentForm/AmendmentForm.js, src/components/LicenseForm/LicenseForm.js
Fixes for release to get rid of console errors and the like
=> fix: fixes

src/settings/components/LicensesCustomProperties.test.js
=> ERM-2276 Add test coverage for ui-licenses settings LicensesCustomProperties

src/LicenseLookup/LicenseLookup.js, src/LicenseLookup/LicenseLookup.test.js, src/LicenseLookup/index.js, translations/ui-licenses/en.json
* create directory, move component
* create index file, write test
* move translation keys to ui-licenses
=> ERM-2258 Add test coverage for ui-licenses LicenseLookup

src/components/License/License.test.js
Tweaked test that previously relied on a missing translation
=> fix: Test translations

src/routes/ViewAmendmentRoute/ViewAmendmentRoute.js
Small tweaks to help console errors
=> chore: Pre release linting

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Updated github workflows to allow use of multiple cores while running jest tests
=> build: github workflows

package.json, src/components/Licenses/Licenses.test.js, src/components/formSections/AmendmentFormInfo/AmendmentFormInfo.test.js, src/components/formSections/LicenseFormInfo/LicenseFormInfo.test.js
Added okapi interface dependency on new licenses interface 5.0
refs ERM-2641
=> build: licenses 5.0

src/components/Amendment/Amendment.js, src/components/AmendmentFilters/AmendmentFilters.js, src/components/AmendmentForm/AmendmentForm.js, src/components/ExportLicenseAsCSVModal/ExportLicenseAsCSVModal.js, src/components/License/License.js, src/components/LicenseFilters/LicenseFilters.js, src/components/LicenseForm/LicenseForm.js, src/constants/errorTypes.js, src/constants/index.js, src/hooks/useLicenseRefdata.js, src/hooks/useLicensesContexts.js, src/routes/AmendmentsRoute/AmendmentsRoute.js, src/routes/CreateAmendmentRoute/CreateAmendmentRoute.js, src/routes/CreateLicenseRoute/CreateLicenseRoute.js, src/routes/EditAmendmentRoute/EditAmendmentRoute.js, src/routes/EditLicenseRoute/EditLicenseRoute.js, src/routes/LicensesRoute/LicensesRoute.js, src/routes/ViewAmendmentRoute/ViewAmendmentRoute.js, src/routes/ViewLicenseRoute/ViewLicenseRoute.js, src/settings/components/LicensesCustomProperties.js, src/settings/index.js, src/settings/routes/PickListSettings.js, src/settings/routes/PickListValueSettings.js
DO NOT MERGE BEFORE https://github.com/folio-org/stripes-erm-components/pull/633
Refactor constants, to take into account tweaks to stripes-erm-components merged along with ERM-2937
=> refactor: Constants

src/components/Amendments/Amendments.js, src/components/Licenses/Licenses.js, src/constants/index.js, src/constants/resultCount.js, src/routes/AmendmentsRoute/AmendmentsRoute.js, src/routes/LicensesRoute/LicensesRoute.js
[ERM-2057](https://issues.folio.org/browse/ERM-2057)
=> ERM-2057, Licenses and Amendments - Implement MCL Next/Previous pagination

src/components/viewSections/LicenseOrganizations/LicenseOrganizations.js
* add org.orgsUuid_object.status to headerStart
=> ERM-3119 Add Organisation status to organisation card display

CHANGELOG.md
=> ERM-3108 ui-licenses release

CHANGELOG.md
Addec changelog section from latest 11.0.2 release
=> chore: Post release 11.0.2

GUIDANCE.md, LICENSE
Updated license and added guidance.md file
=> ERM-3379: Update module license and guidance

src/components/Amendments/Amendments.js, src/components/Licenses/Licenses.js
Removed virtualize prop from multicolumn lists with pagination
=> ERM-3426: Search and sort results MCL scrolling does not work as expected

translations/ui-licenses/en.json
=> ERM-3625 Missing translation key for ui-licenses

CHANGELOG.md, package.json
Bumped dependencies and updated CHANGELOG.md section to reflect release changes
ERM-3415
=> chore: Release 12.0.0

CHANGELOG.md, package.json
Bumped version and updated CANGELOG.md section
ERM-3415
=> chore: Release 12.0.1

CHANGELOG.md, package.json
Bumped version to 12.1.0 and added new CHANGELOG.md section
=> chore: Post release 12.0.1
